name: Buil Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Use Node.js 20x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependecies
      run: npm install
    - name: Execute the unit tests
      run: npm run test:unit
    - name: Display SoftUni username
      run: echo 'marinasokolova'

  execute-UI-test:
    runs-on: ubuntu-latest
    needs: build-and-unit-test
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Use Node.js 20x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependecies
      run: npm install
    - name: Install Playwright browsers
      run:  npx playwright install
    - name: Start the application
      run:  npm run start &
    - name: Execute the UI tests
      run: npm run test:ui

  deploy:
    needs: execute-UI-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_KEY }}
          api-key: ${{ secrets.RENDER_TOKEN }}